blockHeightPayoutDelay: 10
secretPhrase: "<your secret phrase>"
walletUrls:
  - "https://wallet.burst-test.net:8125"
shareExponent: 1.2
poolPublicId: 10282355196851764065
minimumPayout: 250000000000
poolFeeShare: 0.0
poolTxFee: 10000000
minerTxFee: 10000000
deadlineLimit: 10000000000
walletDB:
  user: "root"
  password: ""
  name: "testburstwallet"
db:
  user: "root"
  password: ""
  name: "testburstpool"
feeAccountId: 6418289488649374107
inactiveAfterXBlocks: 10
alpha: 0.02
winnerShare: 0.5
poolPort: 8124
webServerPort: 8080
poolAddress: "http://127.0.0.1"
setWeeklyFee: 100000000
setNowFee: 200000000
setDailyFee: 300000000
setMinPayoutFee: 400000000
nMin: 5
nAVG: 100
tMin: 20
